# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Gravesend Studios
tagline:             'Fine Art across the spectrum'
description:         'Scott Graves'
url:                 http://gravesendstudios.com
baseurl:             /Site
paginate:            7

# About/contact
author:
  name:              Scott Graves
  url:               http://gravesendstudios.com
  email:             sgraves@gravesendstudios.com
# Custom vars
version:             1.0

# Social Media
github:				http://github.com/gravesendstudios
twitter:			
disqus:             

